Internal Server Error: /api/user/make_code/
"POST /api/user/make_code/ HTTP/1.1" 500 34
Internal Server Error: /api/sales_trends/
Traceback (most recent call last):
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Apple/Open_source_project/himool_erp/HimoolERP/apps/statistic/views.py", line 191, in list
    queryset = queryset.extra(select={'date': connection.ops.date_trunc_sql('day', 'create_time')})
TypeError: date_trunc_sql() missing 1 required positional argument: 'params'
"GET /api/sales_trends/?start_date=2025-03-02&end_date=2025-03-10 HTTP/1.1" 500 113333
Internal Server Error: /api/sales_trends/
Traceback (most recent call last):
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Apple/Open_source_project/himool_erp/HimoolERP/apps/statistic/views.py", line 191, in list
    queryset = queryset.extra(select={'date': connection.ops.date_trunc_sql('day', 'create_time')})
TypeError: date_trunc_sql() missing 1 required positional argument: 'params'
"GET /api/sales_trends/?start_date=2025-03-02&end_date=2025-03-10 HTTP/1.1" 500 113333
Internal Server Error: /api/sales_trends/
Traceback (most recent call last):
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Apple/Open_source_project/himool_erp/HimoolERP/apps/statistic/views.py", line 191, in list
    queryset = queryset.extra(select={'date': connection.ops.date_trunc_sql('day', 'create_time')})
TypeError: date_trunc_sql() missing 1 required positional argument: 'params'
"GET /api/sales_trends/?start_date=2025-03-02&end_date=2025-03-10 HTTP/1.1" 500 113334
Internal Server Error: /api/sales_trends/
Traceback (most recent call last):
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Apple/Open_source_project/himool_erp/HimoolERP/apps/statistic/views.py", line 191, in list
    queryset = queryset.extra(select={'date': connection.ops.date_trunc_sql('day', 'create_time')})
TypeError: date_trunc_sql() missing 1 required positional argument: 'params'
"GET /api/sales_trends/?start_date=2025-03-02&end_date=2025-03-10 HTTP/1.1" 500 113333
Internal Server Error: /api/sales_trends/
Traceback (most recent call last):
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Apple/Open_source_project/himool_erp/HimoolERP/apps/statistic/views.py", line 191, in list
    queryset = queryset.extra(select={'date': connection.ops.date_trunc_sql('day', 'create_time')})
TypeError: date_trunc_sql() missing 1 required positional argument: 'params'
"GET /api/sales_trends/?start_date=2025-03-02&end_date=2025-03-10 HTTP/1.1" 500 113335
Internal Server Error: /api/sales_trends/
Traceback (most recent call last):
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Apple/Open_source_project/himool_erp/HimoolERP/apps/statistic/views.py", line 191, in list
    queryset = queryset.extra(select={'date': connection.ops.date_trunc_sql('day', 'create_time')})
TypeError: date_trunc_sql() missing 1 required positional argument: 'params'
"GET /api/sales_trends/?start_date=2025-03-02&end_date=2025-03-10 HTTP/1.1" 500 113333
Internal Server Error: /api/sales_trends/
Traceback (most recent call last):
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Apple/Open_source_project/himool_erp/HimoolERP/apps/statistic/views.py", line 191, in list
    queryset = queryset.extra(select={'date': connection.ops.date_trunc_sql('day', 'create_time')})
TypeError: date_trunc_sql() missing 1 required positional argument: 'params'
"GET /api/sales_trends/?start_date=2025-03-02&end_date=2025-03-10 HTTP/1.1" 500 113333
Internal Server Error: /api/sales_trends/
Traceback (most recent call last):
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Apple/Open_source_project/himool_erp/HimoolERP/apps/statistic/views.py", line 191, in list
    queryset = queryset.extra(select={'date': connection.ops.date_trunc_sql('day', 'create_time')})
TypeError: date_trunc_sql() missing 1 required positional argument: 'params'
"GET /api/sales_trends/?start_date=2025-03-02&end_date=2025-03-10 HTTP/1.1" 500 113376
Internal Server Error: /api/sales_trends/
Traceback (most recent call last):
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Apple/Open_source_project/himool_erp/HimoolERP/apps/statistic/views.py", line 191, in list
    queryset = queryset.extra(select={'date': connection.ops.date_trunc_sql('day', 'create_time')})
TypeError: date_trunc_sql() missing 1 required positional argument: 'params'
"GET /api/sales_trends/?start_date=2025-02-07&end_date=2025-03-10 HTTP/1.1" 500 113374
Internal Server Error: /api/sales_trends/
Traceback (most recent call last):
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Apple/Open_source_project/himool_erp/HimoolERP/apps/statistic/views.py", line 191, in list
    queryset = queryset.extra(select={'date': connection.ops.date_trunc_sql('day', 'create_time')})
TypeError: date_trunc_sql() missing 1 required positional argument: 'params'
"GET /api/sales_trends/?start_date=2025-03-02&end_date=2025-03-10 HTTP/1.1" 500 113374
Internal Server Error: /api/sales_trends/
Traceback (most recent call last):
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Apple/Open_source_project/himool_erp/HimoolERP/apps/statistic/views.py", line 191, in list
    queryset = queryset.extra(select={'date': connection.ops.date_trunc_sql('day', 'create_time')})
TypeError: date_trunc_sql() missing 1 required positional argument: 'params'
"GET /api/sales_trends/?start_date=2025-03-02&end_date=2025-03-10 HTTP/1.1" 500 113374
Internal Server Error: /api/sales_trends/
Traceback (most recent call last):
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Apple/Open_source_project/himool_erp/HimoolERP/apps/statistic/views.py", line 191, in list
    queryset = queryset.extra(select={'date': connection.ops.date_trunc_sql('day', 'create_time')})
TypeError: date_trunc_sql() missing 1 required positional argument: 'params'
"GET /api/sales_trends/?start_date=2025-03-02&end_date=2025-03-10 HTTP/1.1" 500 113374
Internal Server Error: /api/sales_trends/
Traceback (most recent call last):
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Apple/Open_source_project/himool_erp/HimoolERP/apps/statistic/views.py", line 215, in list
    queryset = queryset.extra(select={'date': connection.ops.date_trunc_sql('day', 'create_time')})
TypeError: date_trunc_sql() missing 1 required positional argument: 'params'
"GET /api/sales_trends/?start_date=2025-03-02&end_date=2025-03-10 HTTP/1.1" 500 114351
Internal Server Error: /api/sales_trends/
Traceback (most recent call last):
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Apple/Open_source_project/himool_erp/HimoolERP/apps/statistic/views.py", line 215, in list
    queryset = queryset.extra(select={'date': connection.ops.date_trunc_sql('day', 'create_time')})
TypeError: date_trunc_sql() missing 1 required positional argument: 'params'
"GET /api/sales_trends/?start_date=2025-03-02&end_date=2025-03-10 HTTP/1.1" 500 114350
Internal Server Error: /api/sales_trends/
Traceback (most recent call last):
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Apple/Open_source_project/himool_erp/HimoolERP/apps/statistic/views.py", line 215, in list
    queryset = queryset.extra(select={'date': connection.ops.date_trunc_sql('day', 'create_time')})
TypeError: date_trunc_sql() missing 1 required positional argument: 'params'
"GET /api/sales_trends/?start_date=2025-03-02&end_date=2025-03-10 HTTP/1.1" 500 114360
Internal Server Error: /api/sales_trends/
Traceback (most recent call last):
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Apple/Open_source_project/himool_erp/HimoolERP/apps/statistic/views.py", line 215, in list
    queryset = queryset.extra(select={'date': connection.ops.date_trunc_sql('day', 'create_time')})
TypeError: date_trunc_sql() missing 1 required positional argument: 'params'
"GET /api/sales_trends/?start_date=2025-03-02&end_date=2025-03-10 HTTP/1.1" 500 114360
Internal Server Error: /api/sales_trends/
Traceback (most recent call last):
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Apple/Open_source_project/himool_erp/HimoolERP/apps/statistic/views.py", line 215, in list
    queryset = queryset.extra(select={'date': connection.ops.date_trunc_sql('day', 'create_time')})
TypeError: date_trunc_sql() missing 1 required positional argument: 'params'
"GET /api/sales_trends/?start_date=2025-03-02&end_date=2025-03-10 HTTP/1.1" 500 114361
Internal Server Error: /api/sales_trends/
Traceback (most recent call last):
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Apple/Open_source_project/himool_erp/HimoolERP/apps/statistic/views.py", line 215, in list
    queryset = queryset.extra(select={'date': connection.ops.date_trunc_sql('day', 'create_time')})
TypeError: date_trunc_sql() missing 1 required positional argument: 'params'
"GET /api/sales_trends/?start_date=2025-03-02&end_date=2025-03-10 HTTP/1.1" 500 114360
Internal Server Error: /api/sales_trends/
Traceback (most recent call last):
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Apple/Open_source_project/himool_erp/HimoolERP/apps/statistic/views.py", line 215, in list
    queryset = queryset.extra(select={'date': connection.ops.date_trunc_sql('day', 'create_time')})
TypeError: date_trunc_sql() missing 1 required positional argument: 'params'
"GET /api/sales_trends/?start_date=2025-03-02&end_date=2025-03-10 HTTP/1.1" 500 114360
Internal Server Error: /api/sales_trends/
Traceback (most recent call last):
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/Apple/Library/Python/3.9/lib/python/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Apple/Open_source_project/himool_erp/HimoolERP/apps/statistic/views.py", line 215, in list
    queryset = queryset.extra(select={'date': connection.ops.date_trunc_sql('day', 'create_time')})
TypeError: date_trunc_sql() missing 1 required positional argument: 'params'
"GET /api/sales_trends/?start_date=2025-03-02&end_date=2025-03-10 HTTP/1.1" 500 114360
